-- Create table for storing pokemon stats
-- This is the fact table
-- classification_id is a FK to the classification_id
-- species_id is a FK to the species_id

CREATE TABLE `statistics` (
  `pokemon_id` bigint NOT NULL AUTO_INCREMENT,
  `english_name` varchar(50) NOT NULL,
  `classification_id` bigint DEFAULT NULL,
  `species_id` bigint DEFAULT NULL,
  `hit_points` int DEFAULT NULL,
  `attack` int DEFAULT NULL,
  `defense` int DEFAULT NULL,
  `speed` int DEFAULT NULL,
  `sp_attack` int DEFAULT NULL,
  `sp_defense` int DEFAULT NULL,
  `against_bug` float DEFAULT NULL,
  `against_dark` float DEFAULT NULL,
  `against_dragon` float DEFAULT NULL,
  `against_electric` float DEFAULT NULL,
  `against_fairy` float DEFAULT NULL,
  `against_fight` float DEFAULT NULL,
  `against_fire` float DEFAULT NULL,
  `against_flying` float DEFAULT NULL,
  `against_ghost` float DEFAULT NULL,
  `against_grass` float DEFAULT NULL,
  `against_ground` float DEFAULT NULL,
  `against_ice` float DEFAULT NULL,
  `against_normal` float DEFAULT NULL,
  `against_poison` float DEFAULT NULL,
  `against_psychic` float DEFAULT NULL,
  `against_rock` float DEFAULT NULL,
  `against_steel` float DEFAULT NULL,
  `against_water` float DEFAULT NULL,
  `base_egg_steps` int DEFAULT NULL,
  `base_happiness` int DEFAULT NULL,
  `base_total` int DEFAULT NULL,
  `capture_rate` int DEFAULT NULL,
  `experience_growth` int DEFAULT NULL,
  `height_m` float DEFAULT NULL,
  `weight_kg` float DEFAULT NULL,
  `percentage_male` float DEFAULT NULL,
  `pokedex_number` int DEFAULT NULL,
  `generation` int DEFAULT NULL,
  `is_legendary` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`pokemon_id`),
  UNIQUE KEY `pokemon_id` (`pokemon_id`),
  UNIQUE KEY `english_name` (`english_name`),
  KEY `ndx_classification_id_FK` (`classification_id`),
  KEY `ndx_species_id_FK` (`species_id`),
  CONSTRAINT `classification_id_FK` FOREIGN KEY (`classification_id`) REFERENCES `classification` (`classification_id`),
  CONSTRAINT `species_id_FK` FOREIGN KEY (`species_id`) REFERENCES `species` (`species_id`)
) AUTO_INCREMENT=1;
